services:
  - type: web
    name: staff-of-the-month
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
