services:
  - type: web
    name: fnkaduna-staff1
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
